### ISSUE TITLE
[Request] Show IP Address on Server

### ISSUE THREAD

**Issue by Armi-Heavy** [Maschell/saviine#5]
you can show the IP on the dump or inject, for example in batch archives I add on the first line:

Dump.bat:
> @echo off
> ipconfig | findstr /i "ipv4"
> saviine_server.exe dump

inject.bat:
> @echo off
> ipconfig | findstr /i "ipv4"
> saviine_server.exe inject

**Comment by Bauxite** [comment]
Opened a pull request to add this, with a method that should work on Windows versions from XP on.
